.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH defaults-rs 1  "defaults-rs 0.6.3" 
.SH NAME
defaults\-rs \- Open\-source interface to a user\*(Aqs defaults on macOS
.SH SYNOPSIS
\fBdefaults\-rs\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Open\-source interface to a user\*(Aqs defaults on macOS
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
defaults\-rs\-read(1)
Read a value from domain/plist
.TP
defaults\-rs\-read\-type(1)
Show the type for the given domain/plist path and key
.TP
defaults\-rs\-write(1)
Write a value to domain/plist
.TP
defaults\-rs\-delete(1)
Delete a key or domain/plist
.TP
defaults\-rs\-rename(1)
Rename a key in a domain/plist
.TP
defaults\-rs\-import(1)
Import a plist file
.TP
defaults\-rs\-export(1)
Export a domain/plist to a plist file
.TP
defaults\-rs\-domains(1)
List all available preference domains
.TP
defaults\-rs\-find(1)
List all entries in all domains containing word
.TP
defaults\-rs\-help(1)
Print this message or the help of the given subcommand(s)
.SH VERSION
v0.6.3
